[package]
name = "mqtt_client"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
rumqtt = "0.30.1"
message = { path="../message"}
serde = "1.0.94"
serde_json = "1.0.40"
amiquip = { version = "0.2", default-features = false }
serialport = "3.3.0"
regex = "1.1.9"