[package]
name = "message"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
serialport = "3.3.0"
serde = "1.0.94"
serde_json = "1.0.40"
typetag = "0.1"
hex-literal = "0.2.0"
hex = "0.3.2"
itertools = "0.8.0"